#!/bin/bash
echo "Enter name of Assembly file"
read assemblyFile
gcc -c $assemblyFile -o $assemblyFile.o
echo "Object file Created"
gcc $assemblyFile.o -o $assemblyFile.exe
echo "Executable created"
rm -r $assemblyFile.o
